<a href="https://colab.research.google.com/github/anishareddy04/ML_CSE_21206A/blob/ML_LAB_CODES/ML_LAB7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np
from sklearn.svm import SVR
from sklearn import svm
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [14]:
data = pd.read_excel('t5_train (1).xlsx')

In [ ]:
data


Unnamed: 0.1    Unnamed: 0       embed_0       embed_1       embed_2  \
0                0  0.000000e+00  5.758212e+07  6.776345e+07  2.800258e+07   
1        100000000  8.880995e+04  3.119097e+07  3.410519e+07  3.968865e+07   
2        200000000  1.776199e+05  3.847380e+07  6.444416e+07  5.426541e+07   
3        300000000  2.664298e+05  2.607828e+07  2.149011e+07  2.634352e+07   
4        400000000  3.552398e+05  3.036039e+07  3.340103e+07  2.486513e+07   
...            ...           ...           ...           ...           ...   
1122  112200000000  9.964476e+07  6.174452e+07  3.934451e+07  3.769432e+07   
1123  112300000000  9.973357e+07  6.060619e+07  3.793623e+07  3.743693e+07   
1124  112400000000  9.982238e+07  6.540321e+07  4.104826e+07  4.502261e+07   
1125  112500000000  9.991119e+07  6.864575e+07  3.401918e+07  3.546503e+07   
1126  112600000000  1.000000e+08  7.559972e+07  2.625881e+07  3.440408e+07   

           embed_3       embed_4       embed_5       embed_6       embed_7  \
0     6.299759e+07  6.978351e+07  1.711683e+07  5.645584e+07  7.937437e+07   
1     6.026731e+07  6.183475e+07  3.061917e+07  8.182981e+07  6.866750e+07   
2     4.964486e+07  6.064547e+07  3.750610e+07  3.918242e+07  8.528705e+07   
3     6.323442e+07  5.654922e+07  3.232962e+07  6.189213e+07  5.450312e+07   
4     5.551810e+07  6.740773e+07  2.651439e+07  6.164045e+07  9.178669e+07   
...            ...           ...           ...           ...           ...   
1122  6.154342e+07  5.941496e+07  4.076067e+07  2.463756e+07  3.581907e+07   
1123  5.761607e+07  5.954448e+07  3.602340e+07  2.998996e+07  3.660076e+07   
1124  6.211483e+07  7.146898e+07  4.640262e+07  3.241480e+07  2.983658e+07   
1125  5.827873e+07  6.182658e+07  3.608731e+07  2.447521e+07  3.322754e+07   
1126  5.941596e+07  5.360437e+07  4.426308e+07  2.242577e+07  3.087278e+07   

      ...     embed_758     embed_759     embed_760     embed_761  \
0     ...  2.761353e+07  6.929405e+07  4.151228e+07  5.909623e+07   
1     ...  5.688703e+07  3.626266e+07  2.692882e+07  3.141667e+07   
2     ...  6.649120e+07  8.044265e+07  5.063507e+07  6.075776e+07   
3     ...  6.374082e+07  1.351830e+07  3.554108e+07  3.662709e+07   
4     ...  7.475274e+07  6.132165e+07  4.784321e+07  2.864229e+07   
...   ...           ...           ...           ...           ...   
1122  ...  3.896961e+07  4.506058e+07  4.383869e+07  5.558857e+07   
1123  ...  3.600460e+07  4.291674e+07  3.658945e+07  5.347316e+07   
1124  ...  4.250043e+07  3.925247e+07  5.128983e+07  5.011916e+07   
1125  ...  3.845901e+07  3.649167e+07  1.828804e+07  5.164256e+07   
1126  ...  2.799557e+07  3.575177e+07  3.188954e+07  4.842805e+07   

         embed_762     embed_763     embed_764     embed_765     embed_766  \
0     3.765414e+07  4.017201e+07  6.018143e+07  3.977631e+07  4.195800e+07   
1     8.218112e+07  6.342494e+07  3.680709e+07  2.128675e+07  6.188865e+07   
2     4.996887e+07  5.627393e+07  7.497355e+07  0.000000e+00  3.842391e+07   
3     7.806034e+07  8.068278e+07  4.215658e+07  1.532215e+07  4.028508e+07   
4     6.647345e+07  6.706953e+07  6.027831e+07  3.421864e+07  4.819099e+07   
...            ...           ...           ...           ...           ...   
1122  5.359720e+07  6.048844e+07  5.815135e+07  5.420333e+07  5.798462e+07   
1123  5.364259e+07  5.595120e+07  5.821297e+07  5.862623e+07  5.566659e+07   
1124  4.752961e+07  6.417437e+07  5.967216e+07  5.021099e+07  6.267431e+07   
1125  4.947513e+07  4.944955e+07  5.508058e+07  6.840924e+07  5.894529e+07   
1126  4.718500e+07  3.960551e+07  5.850908e+07  6.342944e+07  5.645050e+07   

         embed_767  
0     3.689091e+07  
1     4.039343e+07  
2     7.024441e+07  
3     4.792073e+07  
4     6.838880e+07  
...            ...  
1122  1.343794e+07  
1123  1.343368e+07  
1124  1.415758e+07  
1125  6.818253e+06  
1126  1.678831e+07  

[1127 rows x 770 columns]

In [ ]:
data = data.apply(lambda x: x*10000)
arr = np.array(data)
x = arr[:, 3:5]
y = arr[:, [4]]
y = y.astype('int')
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)
print(x)
print("\n",y)

[[67763446.33492495 28002576.36981866]
 [34105194.46663083 39688652.15508664]
 [64444161.9627727  54265409.19666092]
 ...
 [41048263.67329707 45022611.46924686]
 [34019176.68232258 35465031.97257904]
 [26258806.74482447 34404080.68167185]]

 [[28002576]
 [39688652]
 [54265409]
 ...
 [45022611]
 [35465031]
 [34404080]]


A1. Train a support vector machine using the training set obtained from above exerciseyou’re yourdataset has multiple classes, take any two classes for this exercise

In [19]:

num_bins=4

data['embed_1_b'] = pd.cut(data['embed_1'], num_bins)
data['embed_12_b'] = pd.cut(data['embed_12'], num_bins)


X = data['embed_1']
y = data['embed_12']
X = X.values.reshape(-1, 1)
y = y.values.reshape(-1, 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
label_encoder = LabelEncoder()
X_train_encoded = label_encoder.fit_transform(X_train)
y_train_encoded = label_encoder.fit_transform(y_train)
X_test_encoded = label_encoder.fit_transform(X_test)
X_test_encoded=X_train_encoded.reshape(-1, 1)
y_test_encoded = label_encoder.fit_transform(y_test)
y_test_encoded=y_train_encoded.reshape(-1, 1)
X_train_encoded=X_train_encoded.reshape(-1, 1)
y_train_encoded= y_train_encoded.reshape(-1, 1)


clf = svm.SVC()

# Train the SVM classifier
clf.fit(X_train_encoded, y_train_encoded)

# Get the support vectors
support_vectors = clf.support_vectors_

# Study the support vectors
print("Number of support vectors:", len(support_vectors))
print("Support Vectors:\n", support_vectors)


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

Number of support vectors: 898
Support Vectors:
 [[212.]
 [139.]
 [667.]
 [667.]
 [220.]
 [194.]
 [547.]
 [800.]
 [169.]
 [602.]
 [626.]
 [786.]
 [629.]
 [130.]
 [496.]
 [484.]
 [569.]
 [214.]
 [704.]
 [279.]
 [320.]
 [458.]
 [597.]
 [ 81.]
 [ 63.]
 [567.]
 [571.]
 [121.]
 [591.]
 [291.]
 [ 90.]
 [152.]
 [637.]
 [499.]
 [384.]
 [316.]
 [265.]
 [503.]
 [222.]
 [300.]
 [607.]
 [463.]
 [317.]
 [415.]
 [399.]
 [767.]
 [719.]
 [151.]
 [417.]
 [354.]
 [355.]
 [201.]
 [556.]
 [715.]
 [327.]
 [541.]
 [712.]
 [552.]
 [603.]
 [243.]
 [329.]
 [682.]
 [368.]
 [ 35.]
 [118.]
 [221.]
 [469.]
 [275.]
 [557.]
 [732.]
 [732.]
 [598.]
 [527.]
 [527.]
 [426.]
 [114.]
 [462.]
 [696.]
 [490.]
 [684.]
 [ 66.]
 [647.]
 [ 92.]
 [123.]
 [366.]
 [366.]
 [653.]
 [751.]
 [483.]
 [170.]
 [655.]
 [730.]
 [727.]
 [190.]
 [563.]
 [332.]
 [332.]
 [695.]
 [422.]
 [215.]
 [100.]
 [688.]
 [115.]
 [622.]
 [627.]
 [627.]
 [633.]
 [213.]
 [640.]
 [739.]
 [621.]
 [568.]
 [472.]
 [165.]
 [737.]
 [656.]
 [ 51.]
 [702.]
 [103.]

A2.support_vectors_A2. Test the accuracy of the SVM using the test set obtained from above exercise. Following code for help.

In [ ]:
# Question A2
clf.score(x,y)

0.7417923691215617

A3. Use the Predict function of SVC classifier to study the output values of the classifier. Relate the output value to the class value predicted. Test the accuracy of the SVM, with your own logic of class determination and comparing against the class labels, using the test set obtained from above exercise.

In [ ]:
# Question A3
clf.predict(x_test)

array([4241, 3390, 5132, 5040, 3006, 5605, 5290, 1707, 5920, 1032, 4550,
       4933, 7642, 6159, 4599, 4291, 4859, 6840, 6192, 6300, 5449, 3394,
       4710, 5654, 5312, 6945, 2696, 5967, 5884, 7160, 3390, 6650, 4552,
       4955, 6926, 3424, 4104, 3243, 7596, 6045, 5620, 3064, 3924, 2875,
       5913, 2420, 4555, 4378, 5953, 8817, 4447, 2634, 3916, 3027, 5916,
       3202, 5613, 3968, 5788, 3072, 6146, 4212, 4029, 5864, 3664, 3530,
       4467, 5256, 4958, 6837, 6198, 4022, 2634, 4656, 4404, 4196, 4447,
       3318, 4846, 5132, 5061, 3638, 5459, 2875, 6840, 5234, 5413, 6481,
       4292, 5517, 6650, 3789, 6636, 6146, 4802, 3352, 5705, 4958, 2450,
       4072, 1860, 4566, 6837, 4356, 1032, 5701, 5864, 5599, 4628, 6344,
       4264, 6837, 3387, 4342, 3816, 1860, 6494, 6945, 4461, 6098, 5748,
       4710, 4707, 3992, 4848, 4920, 5469, 1707, 3992, 6187, 3282, 5808,
       3376, 6945, 6146, 3682, 3935, 3546, 5506, 3031, 7216, 2398, 6281,
       7637, 5792, 4958, 5083, 4072, 3073, 5403, 47

A4. Experiment with various kernel functions (‘linear’, ‘poly’, ‘rbf’&‘sigmoid’) to train and test the accuracy of the models.

In [ ]:
# Question A4
clf = svm.SVC(kernel='linear')
clf.fit(x_train, y_train)
clf.score(x,y)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.5749778172138421

In [ ]:

clf = svm.SVC(kernel='poly')
clf.fit(x_train, y_train)
clf.score(x,y)


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.5749778172138421

In [ ]:

clf = svm.SVC(kernel='rbf')
clf.fit(x_train, y_train)
clf.score(x,y)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.03992901508429459

In [ ]:

clf = svm.SVC(kernel='sigmoid')
clf.fit(x_train, y_train)
clf.score(x,y)


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.005323868677905945